### ISSUE TITLE
Async helpers id being evaluated to$ASYNCID$0$4$

### ISSUE THREAD

**Issue by RamprasadAkella** [doowb/async-helpers#18]
I see the one of the async helper id is being evaluated to "$ASYNCID$0$4$". Can you please let me know what the first number "$0$" indicates and the second number "$4$" indicates ?

**Comment by doowb** [comment]
The first number is a global counter used across all instances of `AsyncHelpers`. The second is a local counter that is used for an individual instance of `AsyncHelpers`. It's mostly for easier debugging and to ensure there aren't duplicate async helper ids in any given string. You shouldn't have to worry about this unless you're having an issue.

I'll close this since it's just a question. If you've found a bug related to this, please reopen the issue and provide more specific information.
